name: "Build"
on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { title: "diag-analyze"    , host: "ubuntu-latest" , arch: "x64"    , cc: "clang"   , conf: "Debug"  , diagnostics: "analyze-build", defs: "ASMJIT_DIR=../asmjit" }
          - { title: "diag-asan"       , host: "ubuntu-latest" , arch: "x64"    , cc: "clang"   , conf: "Release", diagnostics: "address"      , defs: "ASMJIT_DIR=../asmjit,ASMTK_TEST=ON" }
          - { title: "diag-msan"       , host: "ubuntu-latest" , arch: "x64"    , cc: "clang"   , conf: "Release", diagnostics: "memory"       , defs: "ASMJIT_DIR=../asmjit,ASMTK_TEST=ON" }
          - { title: "diag-ubsan"      , host: "ubuntu-latest" , arch: "x64"    , cc: "clang"   , conf: "Release", diagnostics: "undefined"    , defs: "ASMJIT_DIR=../asmjit,ASMTK_TEST=ON" }
          - { title: "diag-valgrind"   , host: "ubuntu-latest" , arch: "x64"    , cc: "clang"   , conf: "Release", diagnostics: "valgrind"     , defs: "ASMJIT_DIR=../asmjit,ASMTK_TEST=ON" }

          - { title: "linux"           , host: "ubuntu-22.04"  , arch: "x86"    , cc: "gcc-12"  , conf: "Debug"  , defs: "ASMJIT_DIR=../asmjit,ASMTK_TEST=ON" }
          - { title: "linux"           , host: "ubuntu-22.04"  , arch: "x86"    , cc: "gcc-12"  , conf: "Release", defs: "ASMJIT_DIR=../asmjit,ASMTK_TEST=ON" }
          - { title: "linux"           , host: "ubuntu-22.04"  , arch: "x64"    , cc: "gcc-12"  , conf: "Debug"  , defs: "ASMJIT_DIR=../asmjit,ASMTK_TEST=ON" }
          - { title: "linux"           , host: "ubuntu-22.04"  , arch: "x64"    , cc: "gcc-12"  , conf: "Release", defs: "ASMJIT_DIR=../asmjit,ASMTK_TEST=ON" }
          - { title: "linux"           , host: "ubuntu-22.04"  , arch: "x86"    , cc: "gcc-13"  , conf: "Debug"  , defs: "ASMJIT_DIR=../asmjit,ASMTK_TEST=ON" }
          - { title: "linux"           , host: "ubuntu-22.04"  , arch: "x86"    , cc: "gcc-13"  , conf: "Release", defs: "ASMJIT_DIR=../asmjit,ASMTK_TEST=ON" }
          - { title: "linux"           , host: "ubuntu-22.04"  , arch: "x64"    , cc: "gcc-13"  , conf: "Debug"  , defs: "ASMJIT_DIR=../asmjit,ASMTK_TEST=ON" }
          - { title: "linux"           , host: "ubuntu-22.04"  , arch: "x64"    , cc: "gcc-13"  , conf: "Release", defs: "ASMJIT_DIR=../asmjit,ASMTK_TEST=ON" }
          - { title: "linux"           , host: "ubuntu-22.04"  , arch: "x86"    , cc: "clang-17", conf: "Debug"  , defs: "ASMJIT_DIR=../asmjit,ASMTK_TEST=ON" }
          - { title: "linux"           , host: "ubuntu-22.04"  , arch: "x86"    , cc: "clang-17", conf: "Release", defs: "ASMJIT_DIR=../asmjit,ASMTK_TEST=ON" }
          - { title: "linux"           , host: "ubuntu-22.04"  , arch: "x64"    , cc: "clang-17", conf: "Debug"  , defs: "ASMJIT_DIR=../asmjit,ASMTK_TEST=ON" }
          - { title: "linux"           , host: "ubuntu-22.04"  , arch: "x64"    , cc: "clang-17", conf: "Release", defs: "ASMJIT_DIR=../asmjit,ASMTK_TEST=ON" }
          - { title: "linux"           , host: "ubuntu-22.04"  , arch: "x86"    , cc: "clang-18", conf: "Debug"  , defs: "ASMJIT_DIR=../asmjit,ASMTK_TEST=ON" }
          - { title: "linux"           , host: "ubuntu-22.04"  , arch: "x86"    , cc: "clang-18", conf: "Release", defs: "ASMJIT_DIR=../asmjit,ASMTK_TEST=ON" }
          - { title: "linux"           , host: "ubuntu-22.04"  , arch: "x64"    , cc: "clang-18", conf: "Debug"  , defs: "ASMJIT_DIR=../asmjit,ASMTK_TEST=ON" }
          - { title: "linux"           , host: "ubuntu-22.04"  , arch: "x64"    , cc: "clang-18", conf: "Release", defs: "ASMJIT_DIR=../asmjit,ASMTK_TEST=ON" }
          - { title: "macos"           , host: "macos-13"      , arch: "x64"    , cc: "gcc-14"  , conf: "Debug"  , defs: "ASMJIT_DIR=../asmjit,ASMTK_TEST=ON" }
          - { title: "macos"           , host: "macos-13"      , arch: "x64"    , cc: "gcc-14"  , conf: "Release", defs: "ASMJIT_DIR=../asmjit,ASMTK_TEST=ON" }
          - { title: "macos"           , host: "macos-13"      , arch: "x64"    , cc: "clang"   , conf: "Debug"  , defs: "ASMJIT_DIR=../asmjit,ASMTK_TEST=ON" }
          - { title: "macos"           , host: "macos-13"      , arch: "x64"    , cc: "clang"   , conf: "Release", defs: "ASMJIT_DIR=../asmjit,ASMTK_TEST=ON" }
          - { title: "windows"         , host: "windows-2022"  , arch: "x86"    , cc: "vs2022"  , conf: "Debug"  , defs: "ASMJIT_DIR=../asmjit,ASMTK_TEST=ON" }
          - { title: "windows"         , host: "windows-2022"  , arch: "x86"    , cc: "vs2022"  , conf: "Release", defs: "ASMJIT_DIR=../asmjit,ASMTK_TEST=ON" }
          - { title: "windows"         , host: "windows-2022"  , arch: "x64"    , cc: "vs2022"  , conf: "Debug"  , defs: "ASMJIT_DIR=../asmjit,ASMTK_TEST=ON" }
          - { title: "windows"         , host: "windows-2022"  , arch: "x64"    , cc: "vs2022"  , conf: "Release", defs: "ASMJIT_DIR=../asmjit,ASMTK_TEST=ON" }

    name: "${{matrix.title}}/${{matrix.arch}}, ${{matrix.cc}} ${{matrix.conf}}"
    runs-on: "${{matrix.host}}"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          path: "asmtk"

      - name: "Checkout AsmJit"
        uses: actions/checkout@v4
        with:
          repository: asmjit/asmjit
          path: "asmjit"

      - name: "Checkout Build Actions"
        uses: actions/checkout@v4
        with:
          repository: build-actions/build-actions
          path: "build-actions"

      - name: "Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: "Build & Test"
        if: ${{!matrix.host}}
        run: python build-actions/action.py
               --step=all
               --compiler=${{matrix.cc}}
               --architecture=${{matrix.arch}}
               --source-dir=asmtk
               --config=asmtk/.github/workflows/build-config.json
               --problem-matcher=auto
               --build-type=${{matrix.build_type}}
               --build-defs=${{matrix.defs}}
